### ISSUE TITLE
Show Extension Status in GitHub List Display 

### ISSUE THREAD

**Issue by reduxionist** [ActivityWatch/aw-watcher-tmux#2]
Thanks for all the code you've shared!

Should this project's GitHub description be updated to show the [Abandoned] status from README? If so, including the pointer to [akohlbecker/aw-watcher-tmux](https://github.com/akohlbecker/aw-watcher-tmux) in the description might also permit setting repository status to "Archived".

For your consideration with thanks!

**Comment by ErikBjare** [comment]
Yes, done!
